/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes.view;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import tubes.controller.paketcontrol;
import tubes.entity.paket;
import tubes.error.tubesEx;
import tubes.event.paketlisten;
import tubes.model.Tabelpaketmodel;
import tubes.model.paketModel;



/**
 *
 * @author HP
 */
public class MainView extends javax.swing.JFrame  {

   
      public MainView() {
        initComponents();
      }

    public void loadDatabase() throws SQLException, tubesEx {
        paketpanel1.loadDatabase();
    }

    
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        BTNHOME = new javax.swing.JButton();
        BTNPAKET = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNLOGOUT = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        HOMEPANEL = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PAKETPANEL = new javax.swing.JPanel();
        paketpanel1 = new tubes.view.paketpanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TUBES");

        bodyPanel.setBackground(new java.awt.Color(52, 73, 94));

        menuPanel.setBackground(new java.awt.Color(52, 73, 94));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        BTNHOME.setBackground(new java.awt.Color(209, 216, 224));
        BTNHOME.setFont(new java.awt.Font("Swis721 Blk BT", 1, 13)); // NOI18N
        BTNHOME.setForeground(new java.awt.Color(52, 73, 94));
        BTNHOME.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-home-64.png")); // NOI18N
        BTNHOME.setText("HOME");
        BTNHOME.setToolTipText("");
        BTNHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHOMEActionPerformed(evt);
            }
        });

        BTNPAKET.setBackground(new java.awt.Color(209, 216, 224));
        BTNPAKET.setFont(new java.awt.Font("Swis721 Blk BT", 1, 13)); // NOI18N
        BTNPAKET.setForeground(new java.awt.Color(52, 73, 94));
        BTNPAKET.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-box-64.png")); // NOI18N
        BTNPAKET.setText("PAKET");
        BTNPAKET.setToolTipText("");
        BTNPAKET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPAKETActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-paper-plane-96.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Magneto", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JPB");

        BTNLOGOUT.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 18)); // NOI18N
        BTNLOGOUT.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-hand-64.png")); // NOI18N
        BTNLOGOUT.setText("KELUAR");
        BTNLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLOGOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNPAKET, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNHOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNLOGOUT, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(BTNHOME, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNPAKET, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNLOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.setBackground(new java.awt.Color(52, 73, 94));
        MainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        MainPanel.setLayout(new java.awt.CardLayout());

        HOMEPANEL.setBackground(new java.awt.Color(52, 73, 94));

        jLabel3.setFont(new java.awt.Font("NewsGoth BT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELAMAT DATANG DI APLIKASI JASA PENGIRIMAN BARANG");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\c3a60fb1820f79094ce8bacf7918dd55.jpg")); // NOI18N

        javax.swing.GroupLayout HOMEPANELLayout = new javax.swing.GroupLayout(HOMEPANEL);
        HOMEPANEL.setLayout(HOMEPANELLayout);
        HOMEPANELLayout.setHorizontalGroup(
            HOMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HOMEPANELLayout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(331, 331, 331))
            .addGroup(HOMEPANELLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HOMEPANELLayout.setVerticalGroup(
            HOMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(94, 94, 94))
        );

        MainPanel.add(HOMEPANEL, "card2");

        PAKETPANEL.setBackground(new java.awt.Color(52, 73, 94));

        paketpanel1.setBackground(new java.awt.Color(52, 73, 94));

        javax.swing.GroupLayout PAKETPANELLayout = new javax.swing.GroupLayout(PAKETPANEL);
        PAKETPANEL.setLayout(PAKETPANELLayout);
        PAKETPANELLayout.setHorizontalGroup(
            PAKETPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paketpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
        );
        PAKETPANELLayout.setVerticalGroup(
            PAKETPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paketpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );

        MainPanel.add(PAKETPANEL, "card3");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHOMEActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll ();
        MainPanel.repaint();
        
        MainPanel.add(HOMEPANEL);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_BTNHOMEActionPerformed

    private void BTNPAKETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPAKETActionPerformed
        // TODO add your handling code here:
         MainPanel.removeAll ();
        MainPanel.repaint();
        
        MainPanel.add(PAKETPANEL);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BTNPAKETActionPerformed

    private void BTNLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLOGOUTActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Apakah Anda Ingin Keluar ","Peringatan" ,dialogBtn);
        
        if (dialogResult == 0 ){
            
            System.exit(0);
        }
        else{
            
        }
        
    }//GEN-LAST:event_BTNLOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHOME;
    private javax.swing.JButton BTNLOGOUT;
    private javax.swing.JButton BTNPAKET;
    private javax.swing.JPanel HOMEPANEL;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PAKETPANEL;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel menuPanel;
    private tubes.view.paketpanel paketpanel1;
    // End of variables declaration//GEN-END:variables

   
}
